# Configuration for the trading environment and simulation
data_file: "equities_daily_close_2018_2023.csv"  # CSV file containing stock data
models_folder: "dqn_trader_models"  # Folder to save model checkpoints
rewards_folder: "dqn_trader_rewards"  # Folder to save rewards
num_episodes: 60  # Number of episodes to train/test
initial_investment: 100000  # Initial investment in USD
transaction_cost_rate: 0.02  # Transaction cost rate

# Hyperparameters for the DQN (Deep Q-Network) agent
batch_size: 32  # Batch size for training
buffer_size: 500  # Size of the replay buffer
gamma: 0.99  # Discount factor
epsilon: 1.0  # Initial exploration rate
epsilon_min: 0.01  # Minimum exploration rate
epsilon_decay: 0.995  # Decay rate for epsilon
alpha: 0.0003  # Learning rate