# Configuration for the trading environment and simulation
data_file: "equities_daily_close_commodities.csv"  # CSV file containing stock data
models_folder: "dqn_trader_models"  # Folder to save model checkpoints
rewards_folder: "dqn_trader_rewards"  # Folder to save rewards
num_episodes: 100  # Number of episodes to train/test
initial_investment: 100000  # Initial investment in USD
transaction_cost_rate: 0.02  # Transaction cost rate

# Hyperparameters for the DQN (Deep Q-Network) agent
batch_size: 32  # Batch size for training
buffer_size: 500  # Size of the replay buffer
epsilon: 1.0  # Initial exploration rate
epsilon_min: 0.01  # Minimum exploration rate

# Configuration 22
# Best selection of hyperparameters from hyperparameter tuning
alpha: 0.0010  # Learning rate
gamma: 0.95  # Discount factor
epsilon_decay: 0.990  # Decay rate for epsilon